# Generated by Django 2.1 on 2018-09-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('contactno', models.CharField(max_length=14, unique=True)),
                ('adminstatus', models.BooleanField(default=False)),
            ],
        ),
    ]
