# Generated by Django 2.1 on 2018-09-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('background', models.ImageField(upload_to='background_images')),
            ],
        ),
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('background', models.ImageField(upload_to='background_images')),
                ('address', models.CharField(max_length=128)),
                ('contactno', models.CharField(max_length=14)),
                ('website', models.URLField(blank=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lodgings', to='home.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='room_images')),
                ('capacity', models.IntegerField()),
                ('size', models.IntegerField()),
                ('features', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='home.Lodging')),
            ],
        ),
    ]
