# Generated by Django 2.1 on 2018-09-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodging',
            name='contactno',
            field=models.CharField(max_length=20),
        ),
    ]
