# Generated by Django 2.1 on 2019-06-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190613_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=13600.0, max_digits=12),
            preserve_default=False,
        ),
    ]
